name: SkynetMonitor

services:
  api:
    build:
      context: ./API_Skynet_Monitor
      dockerfile: Dockerfile
    container_name: SkynetMonitor_API
    env_file:
      - API_Skynet_Monitor/.env
    volumes:
      - skynet_models:/app/models
    expose:
      - "3000"
    restart: unless-stopped
  #  depends_on:
  #    - mysql
    networks:
      - WebSite

  #mysql:
  #  image: mysql:8.0
  #  container_name: SkynetMonitor_MySQL
  #  restart: unless-stopped
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: skynet
  #    MYSQL_USER: skynet
  #    MYSQL_PASSWORD: skynet
  #  volumes:
  #    - skynet_db:/var/lib/mysql
  #  expose:
  #    - "3306"
  #  networks:
  #    - WebSite

volumes:
  skynet_models:
  #skynet_db:

networks:
  WebSite:
    external: true
